### ISSUE TITLE
Error on radar_data

### ISSUE THREAD

**Issue by songsanling** [yizhou-wang/RODNet#16]
Traceback (most recent call last):
  File "tools/train.py", line 199, in <module>
    loss_confmap.backward()
  File "C:\anaconda3\envs\rodnet\lib\site-packages\torch\tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\anaconda3\envs\rodnet\lib\site-packages\torch\autograd\__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

**Comment by yizhou-wang** [comment]
Please give a more detailed explanation, so that I can understand what issue you are facing. Thanks!

**Comment by songsanling** [comment]
Sorry, that is my cuda cudnn issue. Already solved. Thanks.
