### ISSUE TITLE
test.py : No such file or directory

### ISSUE THREAD

**Issue by ghost** [yizhou-wang/RODNet#66]
I get the following error when I try to run tools/test.py:

```
Building model ... ({'type': 'HGv2', 'name': 'rodnet-hg1v2-win16-mnet', 'max_dets': 20, 'peak_thres': 0.4, 'ols_thres': 0.3, 'stacked_num': 1, 'mnet_cfg': (4, 32), 'dcn': False})
Traceback (most recent call last):
  File "tools/test.py", line 145, in <module>
    seq_names = sorted(os.listdir(os.path.join(data_root, dataset_configs['test']['subdir'])))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/disk2/CRUW/ROD2021/sequences/test'
```

This is the command I am running:
`python3 tools/test.py --config configs/config_rodnet_hg1v2_win16_mnet.py --data_dir data/10_10_2022/ --checkpoint checkpoints/rodnet-hg1v2-win16-mnet-20221007-130408/epoch_50_final.pkl --res_dir results/`

**Comment by ghost** [comment]
I modified the config file to have the paths on my computer, and I am not getting the following output:

`Length of testing data: 111
Traceback (most recent call last):
  File "/home/mhpark/RODNet/rodnet/datasets/CRDataset.py", line 158, in __getitem__
    data_dict['image_paths'].append(image_paths[frameid])
TypeError: 'NoneType' object is not subscriptable`

**Comment by Heng-Dickens** [comment]
Have you solved it now? I have the same problem.

**Comment by rastna12** [comment]
Did you find a solution to this issue? I am seeing the same thing
