### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by dollychu** [yizhou-wang/RODNet#72]
Traceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    confmap_preds = rodnet(data.float().cuda())
  File "/home/dolly/anaconda3/envs/rodnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dolly/Desktop/RODNet/rodnet/models/rodnet_cdc.py", line 12, in forward
    x = self.cdc(x)
  File "/home/dolly/anaconda3/envs/rodnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dolly/Desktop/RODNet/rodnet/models/backbones/cdc.py", line 14, in forward
    x = self.encoder(x)
  File "/home/dolly/anaconda3/envs/rodnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dolly/Desktop/RODNet/rodnet/models/backbones/cdc.py", line 47, in forward
    x = self.conv1a(x)  # (B, 2, W, 128, 128) -> (B, 64, W, 128, 128)
  File "/home/dolly/anaconda3/envs/rodnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dolly/anaconda3/envs/rodnet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 479, in forward
    return F.conv3d(input, self.weight, self.bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

I have followed the instructions but it keeps throwing this error message to me, does anyone facing the same problem?

**Comment by fumgmin** [comment]
I also encountered this problem, please ask which version of cuda you are using, I use cuda11.3, A6000 graphics card, currently suspect that the version is too high to match

**Comment by promaxj** [comment]
@dollychu What GPU do you use?
